global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ 'localhost:9090' ]  # Prometheus itself

  - job_name: app
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /metrics  # Adjust if your application serves metrics on a different path
    scheme: http  # Adjust to https if your application uses HTTPS
    tls_config:
      insecure_skip_verify: true  # Adjust for production use
    static_configs:
      - targets:
          - host.docker.internal:8080  # Replace with your application's host and port
