global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: app
    scrape_interval: 30s
    scrape_timeout: 30s
    metrics_path: /metrics
    scheme: http
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - host.docker.internal:8080
