name: Build and Run

on:
  pull_request:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run:
    name: Build, Test, and Coverage
    strategy:
      matrix:
        java-version: [8, 11, 17]
    runs-on: ubuntu-latest

    services:
      slash-db:
        image: postgres:14.1-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - '65432:5432'
        volumes:
          - db:/var/lib/postgresql/data

    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Build and Test
        run: sbt compile clean coverage test coverageReport

      - name: Extract Coverage Summary
        run: |
          # Extract the relevant coverage information from the HTML report
          grep -A 10 "<h1>Code Coverage Summary</h1>" target/scala-3.3.0/scoverage-report/index.html > coverage-summary.md

      - name: Update README
        run: |
          # Insert the coverage summary into README.md
          sed -i '/## Coverage Report/,$d' README.md # Remove existing coverage section
          echo "## Coverage Report" >> README.md
          cat coverage-summary.md >> README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with latest coverage report" || echo "No changes to commit"
          git push
