name: Scala Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install sbt
        run: |
          curl -L --output sbt.zip https://github.com/sbt/sbt/releases/download/v1.6.5/sbt-1.6.5.zip
          unzip sbt.zip
          echo 'export PATH=$HOME/sbt/bin:$PATH' >> $GITHUB_ENV

      - name: Set up Scala
        run: sbt ++3.0.2 setup

      - name: Build and test
        run: sbt test